services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seyeon-oversight
    volumes:
      - ./data:/usr/src/app/data
      - ./apps/oversight/assets:/usr/src/app/assets
    env_file:
      - .env
    network_mode: "host"
    restart: unless-stopped
